Repository dorny/test-reporter, pull requests merged in 2024-06, with the labels that each got.

#225 Add support for NUnit v3 XML results files
  README.md
  __tests__/__outputs__/dotnet-nunit.md
  __tests__/__snapshots__/dotnet-nunit.test.ts.snap
  __tests__/dotnet-nunit.test.ts
  __tests__/fixtures/dotnet-nunit.xml
  __tests__/fixtures/external/nunit-sample.xml
  action.yml
  dist/index.js
  package.json
  reports/dotnet/DotnetTests.NUnitV3Tests/CalculatorTests.cs
  reports/dotnet/DotnetTests.NUnitV3Tests/DotnetTests.NUnitV3Tests.csproj
  reports/dotnet/DotnetTests.sln
  src/main.ts
  src/parsers/dotnet-nunit/dotnet-nunit-parser.ts
  src/parsers/dotnet-nunit/dotnet-nunit-types.ts
  src/parsers/rspec-json/rspec-json-parser.ts
  src/parsers/rspec-json/rspec-json-types.ts
Labels: enhancement

#399 Fix JUnit message / type fields.
  __tests__/__outputs__/swift-xunit.md
  __tests__/__snapshots__/java-junit.test.ts.snap
  __tests__/__snapshots__/swift-xunit.test.ts.snap
  dist/index.js
  src/parsers/java-junit/java-junit-parser.ts
  src/parsers/java-junit/java-junit-types.ts
Labels: bug

#145 Update mocha-json usage instructions
  README.md
Labels: documentation

#134 Fix parsing of ESLint reports in jest-junit format
  __tests__/__outputs__/jest-junit-eslint.md
  __tests__/__snapshots__/jest-junit.test.ts.snap
  __tests__/fixtures/jest-junit-eslint.xml
  __tests__/jest-junit.test.ts
  dist/index.js
  src/parsers/jest-junit/jest-junit-parser.ts
Labels: enhancement
