Repository dorny/test-reporter, pull requests merged in 2024-05, with the labels that each got.

#426 fix: reporting wrong number of tests in Dart
  __tests__/fixtures/empty/dart-json.json
  dist/index.js
  reports/dart/pubspec.lock
  reports/dart/pubspec.yaml
  src/parsers/dart-json/dart-json-parser.ts
Labels: bug, dart

#438 Fix problematic retransmission of authentication token (alternative solution)
  dist/index.js
  src/utils/github-utils.ts
Labels: bug

#442 Update development dependencies
  package-lock.json
  package.json
Labels: dependencies

#419 Update checkout and upload-artifact actions versions
  .github/workflows/check-dist.yml
  .github/workflows/ci.yml
  README.md
Labels: enhancement
