Repository dorny/test-reporter, pull requests merged in 2025-06, with the labels that each got.

#589 Add step summary short summary
  dist/index.js
  src/main.ts
Labels: enhancement

#588 Return links to summary report
  __tests__/__outputs__/dart-json.md
  __tests__/__outputs__/dotnet-nunit.md
  __tests__/__outputs__/dotnet-trx.md
  __tests__/__outputs__/fluent-validation-test-results.md
  __tests__/__outputs__/golang-json.md
  __tests__/__outputs__/jest-junit-eslint.md
  __tests__/__outputs__/jest-junit.md
  __tests__/__outputs__/jest-react-component-test-results.md
  __tests__/__outputs__/jest-test-results.md
  __tests__/__outputs__/junit-with-message.md
  __tests__/__outputs__/mocha-json.md
  __tests__/__outputs__/mocha-test-results.md
  __tests__/__outputs__/provider-test-results.md
  __tests__/__outputs__/pulsar-test-results-no-merge.md
  __tests__/__outputs__/pulsar-test-results.md
  __tests__/__outputs__/rspec-json.md
  __tests__/__outputs__/silent-notes-test-results.md
  __tests__/__outputs__/swift-xunit.md
  dist/index.js
  src/report/get-report.ts
Labels: bug

#605 Configure markdown linting rules
  .markdownlint.json
  README.md
  package.json
Labels: documentation

#606 List only failed tests
  __tests__/__outputs__/dotnet-trx-only-failed.md
  __tests__/__snapshots__/dotnet-trx.test.ts.snap
  __tests__/dotnet-trx.test.ts
  dist/index.js
  src/report/get-report.ts
Labels: bug

#628 Update development dependencies
  package-lock.json
  package.json
Labels: dependencies
