Repository dorny/test-reporter, pull requests merged in 2025-05, with the labels that each got.

#581 Increase step summary limit to 1MiB
  dist/index.js
  src/report/get-report.ts
Labels: enhancement

#582 Fix for empty TRX TestDefinitions
  __tests__/dotnet-trx.test.ts
  __tests__/fixtures/empty/dotnet-trx-empty-test-definitions.trx
  dist/index.js
  src/parsers/dotnet-trx/dotnet-trx-parser.ts
Labels: enhancement

#568 Feature: Add summary title
  README.md
  __tests__/__outputs__/jest-test-results.md
  __tests__/dart-json.test.ts
  __tests__/dotnet-nunit.test.ts
  __tests__/dotnet-trx.test.ts
  __tests__/java-junit.test.ts
  __tests__/jest-junit.test.ts
  __tests__/mocha-json.test.ts
  __tests__/rspec-json.test.ts
  __tests__/swift-xunit.test.ts
  dist/index.js
  src/main.ts
  src/report/get-report.ts
Labels: enhancement

#572 Fix input description for list options
  action.yml
Labels: bug, documentation

#571 Add Golang test parser
  README.md
  __tests__/__outputs__/golang-json.md
  __tests__/__snapshots__/golang-json.test.ts.snap
  __tests__/fixtures/golang-json.json
  __tests__/golang-json.test.ts
  dist/index.js
  package.json
  reports/go/calculator.go
  reports/go/calculator_test.go
  reports/go/go.mod
  src/main.ts
  src/parsers/golang-json/golang-json-parser.ts
  src/parsers/golang-json/golang-json-types.ts
Labels: enhancement

#584 test-reporter release v2.1.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: release
